/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asprojekt.view;

/**
 *
 * @author Kenny Ahlwarth
 */
public class ansichtMitarbeiter extends javax.swing.JPanel {

    /**
     * Creates new form ansichtMItarbeiter
     */
    public ansichtMitarbeiter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSichtMIt = new javax.swing.JLabel();
        lblVname = new javax.swing.JLabel();
        lblNachname = new javax.swing.JLabel();
        lblAdresse = new javax.swing.JLabel();
        lblbday = new javax.swing.JLabel();
        btnSafe = new javax.swing.JButton();
        btnBearbeiten = new javax.swing.JButton();
        txtVorname = new javax.swing.JTextField();
        txtNachname = new javax.swing.JTextField();
        txtAdresse = new javax.swing.JTextField();
        txtBDay = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        lblMitarbeitID = new javax.swing.JLabel();

        lblSichtMIt.setText("Mitarbeiter ID ");

        lblVname.setText("Vorname");

        lblNachname.setText("Nachname");

        lblAdresse.setText("Adresse");

        lblbday.setText("Geburstag");

        btnSafe.setText("Speichern");
        btnSafe.setEnabled(false);
        btnSafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSafeActionPerformed(evt);
            }
        });

        btnBearbeiten.setText("Bearbeiten");
        btnBearbeiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBearbeitenActionPerformed(evt);
            }
        });

        txtVorname.setText("jTextField8");
        txtVorname.setEnabled(false);

        txtNachname.setText("jTextField9");
        txtNachname.setEnabled(false);

        txtAdresse.setText("jTextField10");
        txtAdresse.setEnabled(false);

        txtBDay.setText("jTextField11");
        txtBDay.setEnabled(false);

        btnClear.setText("Clear");
        btnClear.setEnabled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblMitarbeitID.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblAdresse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSichtMIt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNachname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblbday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBDay)
                            .addComponent(txtNachname)
                            .addComponent(txtAdresse)
                            .addComponent(txtVorname)
                            .addComponent(lblMitarbeitID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSafe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBearbeiten)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)
                        .addGap(0, 136, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSichtMIt)
                    .addComponent(lblMitarbeitID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVname)
                    .addComponent(txtVorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNachname)
                    .addComponent(txtNachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdresse)
                    .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbday)
                    .addComponent(txtBDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSafe)
                    .addComponent(btnBearbeiten)
                    .addComponent(btnClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSafeActionPerformed
        // <editor-fold defaultstate="collapsed" desc="Txt und Butten Sichtbarkeit">   
        btnSafe.setEnabled(false);
        btnClear.setEnabled(false);
        btnBearbeiten.setEnabled(true);
        txtAdresse.setEnabled(false);
        txtBDay.setEnabled(false);
        txtNachname.setEnabled(false);
        txtVorname.setEnabled(false);
        // </editor-fold>  

    }//GEN-LAST:event_btnSafeActionPerformed

    private void btnBearbeitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBearbeitenActionPerformed
        // <editor-fold defaultstate="collapsed" desc="Txt und Butten Sichtbarkeit">   
        btnSafe.setEnabled(true);
        btnClear.setEnabled(true);
        btnBearbeiten.setEnabled(false);
        txtAdresse.setEnabled(true);
        txtBDay.setEnabled(true);
        txtNachname.setEnabled(true);
        txtVorname.setEnabled(true);
        // </editor-fold>  

    }//GEN-LAST:event_btnBearbeitenActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtAdresse.setText("");
        txtBDay.setText("");
        txtNachname.setText("");
        txtNachname.setText("");
        txtVorname.setText("");

    }//GEN-LAST:event_btnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBearbeiten;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSafe;
    private javax.swing.JLabel lblAdresse;
    private javax.swing.JLabel lblMitarbeitID;
    private javax.swing.JLabel lblNachname;
    private javax.swing.JLabel lblSichtMIt;
    private javax.swing.JLabel lblVname;
    private javax.swing.JLabel lblbday;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtBDay;
    private javax.swing.JTextField txtNachname;
    private javax.swing.JTextField txtVorname;
    // End of variables declaration//GEN-END:variables
}
