/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asprojekt.view;

import asprojekt.model.Geraet;

/**
 *
 * @author Kenny Ahlwarth
 */
public class ansichtGeraete extends javax.swing.JPanel {

    /**
     * Creates new form ansichGeraete
     */
    public ansichtGeraete() {
        initComponents();
    }
        public ansichtGeraete(Geraet g) {
        initComponents();
        setInfos(g);
    }
        
    public void setInfos(Geraet g){
//        try{
        lblshowNameG.setText(g.getNetconfig().getDns_name());
        lblShSnNR.setText(g.getSn());
        lblshowPreis.setText(String.valueOf(g.getAnschPreis()));
        lblshowOrt.setText(g.getStandort());
        lblShowRaum.setText(g.getRaum().getRaumNr());
//        }catch(Exception e){
//            System.out.println("Bleb");
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblueberGaert = new javax.swing.JLabel();
        lblshowNameG = new javax.swing.JLabel();
        lblSnNr = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblOrt = new javax.swing.JLabel();
        lblShSnNR = new javax.swing.JLabel();
        lblshowPreis = new javax.swing.JLabel();
        lblshowOrt = new javax.swing.JLabel();
        lblRaumNr = new javax.swing.JLabel();
        lblShowRaum = new javax.swing.JLabel();

        lblueberGaert.setText("Gerät Übersicht");

        lblshowNameG.setText("jLabel1");

        lblSnNr.setText("Serien-Nr");

        jLabel1.setText("Anschaffungspreis");

        lblOrt.setText("Standort");

        lblShSnNR.setText("jLabel2");

        lblshowPreis.setText("jLabel3");

        lblshowOrt.setText("jLabel4");

        lblRaumNr.setText("Raum-Nr.");

        lblShowRaum.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRaumNr, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblShowRaum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblSnNr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblOrt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblueberGaert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblshowNameG, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(lblShSnNR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblshowPreis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblshowOrt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblueberGaert)
                    .addComponent(lblshowNameG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSnNr)
                    .addComponent(lblShSnNR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblshowPreis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrt)
                    .addComponent(lblshowOrt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaumNr)
                    .addComponent(lblShowRaum))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblOrt;
    private javax.swing.JLabel lblRaumNr;
    private javax.swing.JLabel lblShSnNR;
    private javax.swing.JLabel lblShowRaum;
    private javax.swing.JLabel lblSnNr;
    private javax.swing.JLabel lblshowNameG;
    private javax.swing.JLabel lblshowOrt;
    private javax.swing.JLabel lblshowPreis;
    private javax.swing.JLabel lblueberGaert;
    // End of variables declaration//GEN-END:variables
}
