/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asprojekt.view;

import asprojekt.model.Geraet;
import javax.swing.JFrame;

/**
 *
 * @author Kenny Ahlwarth
 */
public class ansichtConfi extends javax.swing.JPanel {

    /**
     * Creates new form ansichtConfi
     */
    private Geraet g;
    private JFrame jf;

    public ansichtConfi() {
        initComponents();
    }

    public void setJf(JFrame jf) {
        this.jf = jf;
    }

    public ansichtConfi(Geraet g) {
        initComponents();
        this.g = g;
        fillConfig();
    }

    public void fillConfig() {
        txtDNS_Name.setText(g.getNetconfig().getDns_name());
        txtDNS.setText(g.getNetconfig().getDns_server());
        txtIP.setText(g.getNetconfig().getIp_adresse());
        txtMAC.setText(g.getNetconfig().getMac());
        txtMaske.setText(g.getNetconfig().getNetzmaske());
        txtRate.setText(String.valueOf(g.getNetconfig().getUebertragungsrate()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMac = new javax.swing.JLabel();
        lblRate = new javax.swing.JLabel();
        lblNetzmaske = new javax.swing.JLabel();
        lblIP = new javax.swing.JLabel();
        lblDNS = new javax.swing.JLabel();
        txtDNS_Name = new javax.swing.JTextField();
        txtRate = new javax.swing.JTextField();
        txtMaske = new javax.swing.JTextField();
        txtIP = new javax.swing.JTextField();
        txtDNS = new javax.swing.JTextField();
        btnSafe = new javax.swing.JButton();
        btnBearbeiten = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMAC = new javax.swing.JTextField();
        btnEnd = new javax.swing.JButton();

        jLabel1.setText("Confi");

        lblMac.setText("DNS-Name");

        lblRate.setText("Übertragunsrate");

        lblNetzmaske.setText("Netzmaske");

        lblIP.setText("IP-Adresse");

        lblDNS.setText("DNS");

        txtDNS_Name.setText("jTextField1");
        txtDNS_Name.setEnabled(false);

        txtRate.setText("jTextField2");
        txtRate.setEnabled(false);

        txtMaske.setText("jTextField3");
        txtMaske.setEnabled(false);

        txtIP.setText("jTextField4");
        txtIP.setEnabled(false);

        txtDNS.setText("jTextField5");
        txtDNS.setEnabled(false);

        btnSafe.setText("Speichern");
        btnSafe.setEnabled(false);
        btnSafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSafeActionPerformed(evt);
            }
        });

        btnBearbeiten.setText("Bearbeiten ");
        btnBearbeiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBearbeitenActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.setEnabled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel2.setText("MAC");

        txtMAC.setText("jTextField5");
        txtMAC.setEnabled(false);
        txtMAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMACActionPerformed(evt);
            }
        });

        btnEnd.setText("OK");
        btnEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(lblRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNetzmaske, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDNS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMAC)
                            .addComponent(txtDNS_Name)
                            .addComponent(txtRate)
                            .addComponent(txtMaske)
                            .addComponent(txtIP)
                            .addComponent(txtDNS))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEnd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(btnSafe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBearbeiten)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMac)
                    .addComponent(txtDNS_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRate)
                    .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNetzmaske)
                    .addComponent(txtMaske, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIP, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDNS)
                    .addComponent(txtDNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSafe)
                    .addComponent(btnBearbeiten)
                    .addComponent(btnClear)
                    .addComponent(btnEnd))
                .addGap(0, 31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSafeActionPerformed
        // TODO add your handling code here:
        txtDNS.setEnabled(false);
        txtIP.setEnabled(false);
        txtDNS_Name.setEnabled(false);
        txtMaske.setEnabled(false);
        txtRate.setEnabled(false);
        btnClear.setEnabled(false);
        btnSafe.setEnabled(false);
    }//GEN-LAST:event_btnSafeActionPerformed

    private void btnBearbeitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBearbeitenActionPerformed
        // TODO add your handling code here:
        txtDNS.setEnabled(true);
        txtIP.setEnabled(true);
        txtDNS_Name.setEnabled(true);
        txtMaske.setEnabled(true);
        txtRate.setEnabled(true);
        btnClear.setEnabled(true);
        btnSafe.setEnabled(true);
    }//GEN-LAST:event_btnBearbeitenActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        txtDNS.setText("");
        txtIP.setText("");
        txtDNS_Name.setText("");
        txtMaske.setText("");
        txtRate.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtMACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMACActionPerformed

    private void btnEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndActionPerformed
        // TODO add your handling code here:
        jf.dispose();
    }//GEN-LAST:event_btnEndActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBearbeiten;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnSafe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDNS;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblMac;
    private javax.swing.JLabel lblNetzmaske;
    private javax.swing.JLabel lblRate;
    private javax.swing.JTextField txtDNS;
    private javax.swing.JTextField txtDNS_Name;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtMAC;
    private javax.swing.JTextField txtMaske;
    private javax.swing.JTextField txtRate;
    // End of variables declaration//GEN-END:variables
}
