/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asprojekt.view;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;

/**
 *
 * @author Kenny Ahlwarth
 */
public class Hauptmenue extends javax.swing.JPanel {

    /**
     * Creates new form Hauptm
     */
    public Hauptmenue() {
        initComponents();

        //Group the radio buttons.
        ButtonGroup auswahl;
        auswahl = new ButtonGroup();
        auswahl.add(jbtnGeraete);
        auswahl.add(jbtnMitarbeiter);

        btnloeschen.setEnabled(false);
        MenuePanel.setBackground(Color.red);
        while (jbtnMitarbeiter.isSelected()) {
            btnConf.setEnabled(false);
            btnWartungen.setEnabled(false);
            btnmore.setEnabled(false);

        }
    }
    /**
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    //Group the radio buttons.
    ButtonGroup group = new ButtonGroup();

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUebersicht = new javax.swing.JList<>();
        txtSuche = new javax.swing.JTextField();
        btnHinzu = new javax.swing.JButton();
        btnloeschen = new javax.swing.JButton();
        jbtnGeraete = new javax.swing.JRadioButton();
        jbtnMitarbeiter = new javax.swing.JRadioButton();
        btnConf = new javax.swing.JButton();
        btnWartungen = new javax.swing.JButton();
        MenuePanel = new javax.swing.JPanel();
        btnmore = new javax.swing.JButton();

        lstUebersicht.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstUebersicht.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUebersichtValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstUebersicht);

        txtSuche.setText("Suche ");
        txtSuche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSucheMouseClicked(evt);
            }
        });

        btnHinzu.setText("+");
        btnHinzu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHinzuActionPerformed(evt);
            }
        });

        btnloeschen.setText("-");
        btnloeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloeschenActionPerformed(evt);
            }
        });

        jbtnGeraete.setSelected(true);
        jbtnGeraete.setText("Geräte");
        jbtnGeraete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGeraeteActionPerformed(evt);
            }
        });

        jbtnMitarbeiter.setText("Mitarbeiter");
        jbtnMitarbeiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMitarbeiterActionPerformed(evt);
            }
        });

        btnConf.setText("Confi");
        btnConf.setEnabled(false);

        btnWartungen.setText("Wartung");
        btnWartungen.setEnabled(false);
        btnWartungen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWartungenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuePanelLayout = new javax.swing.GroupLayout(MenuePanel);
        MenuePanel.setLayout(MenuePanelLayout);
        MenuePanelLayout.setHorizontalGroup(
            MenuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MenuePanelLayout.setVerticalGroup(
            MenuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnmore.setText("Infos");
        btnmore.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnGeraete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnMitarbeiter)
                                .addGap(14, 14, 14)
                                .addComponent(btnHinzu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnloeschen))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnWartungen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnmore)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(MenuePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(txtSuche, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSuche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHinzu)
                    .addComponent(btnloeschen)
                    .addComponent(jbtnGeraete)
                    .addComponent(jbtnMitarbeiter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MenuePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConf)
                            .addComponent(btnWartungen)
                            .addComponent(btnmore)))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHinzuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHinzuActionPerformed

        if (jbtnGeraete.isSelected()) {
            JFrame jf = new JFrame("Hinzufügen eines Gerätes");
            jf.setSize(400, 250);
            jf.add(new hinzuGeraet());
            jf.setVisible(true);
        } else {
            JFrame jf = new JFrame("Mitarbeiter Erstellung ");
            jf.setSize(400, 250);
            jf.add(new hinzuMitarbeiter());
            jf.setVisible(true);
        }
    }//GEN-LAST:event_btnHinzuActionPerformed

    private void jbtnGeraeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGeraeteActionPerformed
        btnWartungen.setVisible(true);
        btnConf.setVisible(true);
        btnmore.setVisible(true);
    }//GEN-LAST:event_jbtnGeraeteActionPerformed

    private void lstUebersichtValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstUebersichtValueChanged
        btnloeschen.setEnabled(true);
        btnWartungen.setEnabled(true);
        btnConf.setEnabled(true);
        btnmore.setEnabled(true);
    }//GEN-LAST:event_lstUebersichtValueChanged

    private void jbtnMitarbeiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMitarbeiterActionPerformed
        btnWartungen.setVisible(false);
        btnConf.setVisible(false);
        btnmore.setVisible(false);
    }//GEN-LAST:event_jbtnMitarbeiterActionPerformed

    private void txtSucheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSucheMouseClicked
        txtSuche.setText(" ");
    }//GEN-LAST:event_txtSucheMouseClicked

    private void btnloeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloeschenActionPerformed
        //  while (lstUebersicht.getSelectedValue() != null) {
        //   }
    }//GEN-LAST:event_btnloeschenActionPerformed

    private void btnWartungenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWartungenActionPerformed
        // TODO add your handling code here:
        JFrame jf = new JFrame("Wartungs Menü");
        jf.setSize(600, 600);
        jf.add(new ansichtWartung());
        jf.setVisible(true);

    }//GEN-LAST:event_btnWartungenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuePanel;
    private javax.swing.JButton btnConf;
    private javax.swing.JButton btnHinzu;
    private javax.swing.JButton btnWartungen;
    private javax.swing.JButton btnloeschen;
    private javax.swing.JButton btnmore;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jbtnGeraete;
    private javax.swing.JRadioButton jbtnMitarbeiter;
    private javax.swing.JList<String> lstUebersicht;
    private javax.swing.JTextField txtSuche;
    // End of variables declaration//GEN-END:variables
}
