/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asprojekt.view;

import com.sun.java.accessibility.util.AWTEventMonitor;
import java.awt.event.WindowListener;
import javax.swing.JFrame;
import sun.awt.windows.WLightweightFramePeer;

/**
 *
 * @author Kenny Ahlwarth
 */
public class hinzuGeraet extends javax.swing.JPanel {

    /**
     * Creates new form hintuGeraet
     */
    private JFrame jf;
    private Hauptmenue hauptmenue;

    public hinzuGeraet() {
        initComponents();

    }

    public void setHauptmenue(Hauptmenue hauptmenue) {
        this.hauptmenue = hauptmenue;
    }

    public void setJf(JFrame jf) {
        this.jf = jf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNew = new javax.swing.JLabel();
        lblGName = new javax.swing.JLabel();
        lblSerienNr = new javax.swing.JLabel();
        lblPreis = new javax.swing.JLabel();
        lblOrt = new javax.swing.JLabel();
        txtGName = new javax.swing.JTextField();
        txtSnNr = new javax.swing.JTextField();
        txtPreis = new javax.swing.JTextField();
        txtOrt = new javax.swing.JTextField();
        btnSpeichern = new javax.swing.JButton();
        btnAbbruch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblRaumNr = new javax.swing.JLabel();
        txtRaumNr = new javax.swing.JTextField();

        lblNew.setText("Neues Gerät ");

        lblGName.setText("Geräte Name ");

        lblSerienNr.setText("Serien-Nr");

        lblPreis.setText("Anschaffungspreis");

        lblOrt.setText("Standort");

        txtGName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGNameActionPerformed(evt);
            }
        });

        btnSpeichern.setText("Speichern ");
        btnSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeichernActionPerformed(evt);
            }
        });

        btnAbbruch.setText("Abbruch");
        btnAbbruch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbbruchActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblRaumNr.setText("Raum-Nr.");

        txtRaumNr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRaumNrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSpeichern)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAbbruch)
                        .addGap(26, 26, 26)
                        .addComponent(btnClear)
                        .addGap(0, 141, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblRaumNr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPreis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSerienNr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOrt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSnNr)
                            .addComponent(txtPreis)
                            .addComponent(txtGName)
                            .addComponent(txtOrt)
                            .addComponent(txtRaumNr))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGName)
                    .addComponent(txtGName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerienNr)
                    .addComponent(txtSnNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreis)
                    .addComponent(txtPreis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrt)
                    .addComponent(txtOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaumNr)
                    .addComponent(txtRaumNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpeichern)
                    .addComponent(btnAbbruch)
                    .addComponent(btnClear))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGNameActionPerformed

    private void btnSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeichernActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSpeichernActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtGName.setText("");
        txtSnNr.setText("");
        txtOrt.setText("");
        txtPreis.setText("");
        txtRaumNr.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAbbruchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbbruchActionPerformed
        // TODO add your handling code here:
        jf.dispose();
    }//GEN-LAST:event_btnAbbruchActionPerformed

    private void txtRaumNrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRaumNrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRaumNrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbbruch;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSpeichern;
    private javax.swing.JLabel lblGName;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblOrt;
    private javax.swing.JLabel lblPreis;
    private javax.swing.JLabel lblRaumNr;
    private javax.swing.JLabel lblSerienNr;
    private javax.swing.JTextField txtGName;
    private javax.swing.JTextField txtOrt;
    private javax.swing.JTextField txtPreis;
    private javax.swing.JTextField txtRaumNr;
    private javax.swing.JTextField txtSnNr;
    // End of variables declaration//GEN-END:variables

}
