/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asprojekt.view.ansicht;

import javax.swing.JFrame;
import asprojekt.view.hinzufuegen.hinzuMitarbeiter;
import asprojekt.view.hinzufuegen.hinzuWartung;

/**
 *
 * @author Kenny Ahlwarth
 */
public class ansichtWartung extends javax.swing.JPanel {

    /**
     * Creates new form ansichtWartung
     */
    public ansichtWartung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWartungsPro = new javax.swing.JLabel();
        lblLetzteWartung = new javax.swing.JLabel();
        lblWartungenGes = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnADD = new javax.swing.JButton();
        lblDatumLetzWartun = new javax.swing.JLabel();
        lblLetzterBearbeitung = new javax.swing.JLabel();
        lblLetzterBearbeiter = new javax.swing.JLabel();
        lblWartungengesAnzeige = new javax.swing.JLabel();
        lblNameGeraet = new javax.swing.JLabel();

        lblWartungsPro.setText("Wartungs Protkoll");

        lblLetzteWartung.setText("Letzte Wartung ");

        lblWartungenGes.setText("Durchfühte Wartungen ");

        btnClose.setText("OK ");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnADD.setText("Hinzufügen");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        lblDatumLetzWartun.setText("jLabel5");

        lblLetzterBearbeitung.setText("letzter Bearbeiter/in");

        lblLetzterBearbeiter.setText("jLabel8");

        lblWartungengesAnzeige.setText("jLabel9");

        lblNameGeraet.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnADD))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblLetzterBearbeitung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblWartungsPro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWartungenGes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLetzteWartung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatumLetzWartun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLetzterBearbeiter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblWartungengesAnzeige, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNameGeraet, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWartungsPro)
                    .addComponent(lblNameGeraet))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLetzteWartung)
                    .addComponent(lblDatumLetzWartun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLetzterBearbeitung)
                    .addComponent(lblLetzterBearbeiter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWartungenGes)
                    .addComponent(lblWartungengesAnzeige))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnADD))
                .addGap(0, 13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        JFrame jf = new JFrame("Wartungs Menü");
        jf.setSize(600, 600);
        jf.add(new hinzuWartung());
        jf.setVisible(true);
    }//GEN-LAST:event_btnADDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblDatumLetzWartun;
    private javax.swing.JLabel lblLetzteWartung;
    private javax.swing.JLabel lblLetzterBearbeiter;
    private javax.swing.JLabel lblLetzterBearbeitung;
    private javax.swing.JLabel lblNameGeraet;
    private javax.swing.JLabel lblWartungenGes;
    private javax.swing.JLabel lblWartungengesAnzeige;
    private javax.swing.JLabel lblWartungsPro;
    // End of variables declaration//GEN-END:variables
}
